Build a conference website
fahdrahali/conference pull request #2
Opened 2022-03-10 01:58 UTC by fahdrahali

**build a conference website:**
- Use semantic HTML tags.
- Use CSS box model.
- Use Flexbox to place elements on the page.
- Create two screen sizes using media queries, mobile, and desktop.
- Use objects to store and access data.
- Use JavaScript to manipulate DOM elements.
- Use JavaScript events.
- Use GitHub Pages to deploy web pages.

2022-03-10 04:04 UTC, keroloussamy requested changes
Hi @fahdrahali, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-10 04:04 UTC, keroloussamy commented on README.md
> +
- [x] Kindly in the Getting started section you can add steps to how anyone can use this project. And you can move what you write in it under the project name, as it's a description for the project.

like 
```
To get a local copy up and running follow these simple example steps.

- Click on the top right green "code" button.
- On the dropdown menu, choose "download with zip" button.
- After download, extract the zip file and you have the project running on your machine.
```

2022-03-10 04:04 UTC, keroloussamy commented on README.md
> +
- [x] Kindly add the "Acknowledgements" section that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the requirements.

like 

Acknowledgments

- Inspired by [Cindy Shin](https://www.behance.net/adagio07)
- The design link [original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)

2022-03-10 04:04 UTC, keroloussamy commented on README.md
> +
- [x] Kindly add the `Live Demo` section, upload your page on GitHub pages and add the link here, so any one can see your page.

2022-03-10 04:04 UTC, keroloussamy commented on index.html
> +
- [x] Kindly add the `Main Program` section to your page as in the design,

This one
![image](https://user-images.githubusercontent.com/35535130/157583115-360e9fd8-6b6c-49fd-a522-9fc110e17967.png)

2022-03-10 04:04 UTC, keroloussamy commented on index.html
> +
- [x] Kindly add the `Partners` section to your page as in the design.

This one
![image](https://user-images.githubusercontent.com/35535130/157583606-98aa9adb-7051-4ff3-b3dd-f399117e95a8.png)

2022-03-10 04:04 UTC, keroloussamy commented on index.html
> +
- [x]  Kindly add the `Footer` section to your page as in the design. You should have the logo on the left and the content on the right.

This one 
![image](https://user-images.githubusercontent.com/35535130/157583717-061f5078-e494-49e2-8f5a-4c76855ae552.png)

2022-03-10 04:04 UTC, keroloussamy commented on index.js
> +}
- [x] Good job add this part by JS dynamically, it's just a small problem is some text goes on each other kindly fix it, to make it clear for every one try to read.

![image](https://user-images.githubusercontent.com/35535130/157584236-0e0353e8-cdd3-44cc-aa95-18fd59f9bf50.png)

2022-03-10 04:04 UTC, keroloussamy commented on html/about.html
> +    </section>
- [x] Kindly add this section to your page as in the design. In the about page.

![image](https://user-images.githubusercontent.com/35535130/157584437-162d48da-dc94-429e-a23c-51b7d199eaa6.png)

2022-03-10 04:04 UTC, keroloussamy commented on html/about.html
> +    </section>
- [x]  Kindly add this section to your page as in the design. In the about page.

This one
![image](https://user-images.githubusercontent.com/35535130/157584656-25f7e772-1f87-48ef-9e4d-74e7cd03ec4a.png)

2022-03-10 04:04 UTC, keroloussamy commented on html/about.html
> +</section>
- [x] Kindly add the Footer section to your page as in the design. You should have the logo on the left and the content on the right.

![image](https://user-images.githubusercontent.com/35535130/157584762-e78748f4-5d16-48cc-9cd0-11073fbc898c.png)

2022-03-10 04:04 UTC, keroloussamy commented on style.css
> +  }
- [x] Kindly this title make your page overflow the with, kindly fix the title with.

![image](https://user-images.githubusercontent.com/35535130/157585096-d0a255ab-bf50-4bf7-a577-9fe7c04c8df6.png)

2022-03-10 04:04 UTC, keroloussamy commented on style.css
> +  }
- [x] Kindly make your menu background take the whole height of the page, to make you design better.

![image](https://user-images.githubusercontent.com/35535130/157585383-846d75a3-8aea-427d-9b07-3600b338a7ab.png)

2022-03-10 04:04 UTC, keroloussamy commented on index.html
> +                <li><a href="#">CC Campaign</a></li>
- [x] Kindly when I be on the About page there's no link to take me back for the Home page, Kindly add a link for the home page in the about page.

![image](https://user-images.githubusercontent.com/35535130/157585794-ba845c42-9116-485a-bcf0-c2df3233a9ec.png)

2022-03-10 04:04 UTC, keroloussamy commented on .github/workflows/linters.yml
> +        run: npx stylelint "**/*.{css,scss}"
- [ ] Kindly add the JS linter also here to be checked also, use this [template](https://github.com/microverseinc/linters-config/tree/master/html-css-js) it's for html-css-js projects.

2022-03-12 00:15 UTC, medaminedev66 requested changes
Hi @fahdrahali 😃, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-12 00:15 UTC, medaminedev66 commented on html/about.html
> +</main>
- [x] In mobile version: Kindly add all the about page sections that are provided in the template. I can see many sections of the about page (project logo, see the past, partners, footer...) are not shown on the mobile version:
- Original design:
<img width="106" alt="image" src="https://user-images.githubusercontent.com/77190203/157991679-9df2f88f-146f-4ec6-9468-f13db48d0ccc.png">

2022-03-12 00:15 UTC, medaminedev66 commented on index.html
> +        </article>
- [x] Kindly stick to the provided template as match as you can. Kindly add gaps between cards, and add paddings to the left and the right of the main program section.
- Your design:
<img width="206" alt="image" src="https://user-images.githubusercontent.com/77190203/157992940-50599dcc-8e45-43a5-8a10-75b2c726b177.png">


- Original design:
<img width="209" alt="image" src="https://user-images.githubusercontent.com/77190203/157992802-6b3161b4-2f6b-4e9b-8704-89300a5ca99e.png">

2022-03-12 00:15 UTC, medaminedev66 commented on style.css
> +@media screen and (max-width: 768px) {
[OPTIONAL] In the desktop version, your page is scrolling horizontally. It would be better to fix the width of the pages and make sure that the page doesn't have a horizontal bar to improve your UI design.

<img width="959" alt="image" src="https://user-images.githubusercontent.com/77190203/157993649-14ca55b8-0a54-404e-8f75-361cd45e1b1a.png">

2022-03-12 00:15 UTC, medaminedev66 commented on README.md
> +[Conference](https://fahdrahali.github.io/)
- [ ] The live demo link is broken. kindly make sure that your project is deployed and add the link of the online version of your project to your README.

2022-03-12 00:15 UTC, medaminedev66 commented on html/about.html
> +</footer>
- [ ] Following the project requirements, the logo should be added to the footer. Kindly add the same logo you used in the header to the footer.
<img width="947" alt="image" src="https://user-images.githubusercontent.com/77190203/157994295-220d9f52-e0a3-4587-8856-9e5c1d84179e.png">

2022-03-12 00:25 UTC, fahdrahali commented on README.md
> +[Conference](https://fahdrahali.github.io/)
The link isn't broken. when I will merge the pull request, it will work.

2022-03-12 18:04 UTC, Donard97 approved these changes
## Hello @fahdrahali , 👋  

_You did a tremendous job of implementing all required changes from the other reviewers.  💯 👏_ 

**_Your project is complete!  There is nothing else to say other than... it's time to merge it 💪 👏_** 

## Highlights ✅ 

- PR is descriptive ✔️ 
- Readme file is professional ✔️ 
- Code is clean ✔️ 
- There is no linter error ✔️ 
- Live link is working ✔️ 

## Congratulations! 🎉 🎉 🎉 

![giphy (4)](https://user-images.githubusercontent.com/74506933/158029346-55387b82-bcb4-4de1-a3b6-d5c777770367.gif)

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-04-08 08:11 UTC, merged